# Generated by Django 5.2.7 on 2025-11-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('TAMIL', 'Tamil'), ('HINDI', 'Hindi'), ('ENGLISH', 'English'), ('TELUGU', 'Telugu'), ('MALAYALAM', 'Malayalam'), ('KANNADA', 'Kannada')], default='TAMIL', max_length=20),
        ),
    ]
